.shared-rules:
  skip-if-docs-only: &skip-if-docs-only
    if: '$CI_COMMIT_MESSAGE =~ /\Adocs:/'
    when: never

build:
  stage: build
  image: docker:19.03.5
  services:
    - docker:19.03.5-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  rules:
    - <<: *skip-if-docs-only
    - when: on_success
  script:
    - >-
       docker build
       --build-arg "HELM_VERSION=$HELM_VERSION"
       --build-arg "KUBERNETES_VERSION=$KUBERNETES_VERSION"
       --build-arg "ALPINE_VERSION=$ALPINE_VERSION"
       --build-arg "GLIBC_VERSION=$GLIBC_VERSION"
       --tag "$BUILD_IMAGE_NAME" .
    - docker push "$BUILD_IMAGE_NAME"
    - export latest_tag="${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_SLUG}:latest"
    - docker tag "$BUILD_IMAGE_NAME" $latest_tag
    - docker push $latest_tag
